### ISSUE TITLE
Make Docker tag selectable?!

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/gh-render-action#1]
Can we introduce a choice WHAT Docker tag should be used?

For example,
`t3docs/render-documentation` is `t3docs/render-documentation:latest`, which is `v2.8.3`

But,
`t3docs/render-documentation:develop` ist `v2.9-dev` at the moment and release candidate for `v2.9.0`.

Can we make the tag, that is, `latest` or `develop` configurable?

I would be nice if we could render some example manuals on the server with the new version.

**Comment by susannemoog** [comment]
We can make it configurable in general, that wouldn't be a problem - however, it would probably not achieve your goal, because we cannot "render some example manuals" with another version on the server: we don't render on the server at all, but with GitHub actions itself and the rendering uses the exact same config for all rendered manuals. We could switch the chain for a day and see what happens, OR (and this is what I would prefer) I could re-render the manuals locally with the new container, check some of them and then do that on the server.

**Comment by marble** [comment]
There is a lot that can be considered; it's probably better we talk about that.
For now I did exactly that: render locally, upload as GitHub pages: https://typo3-documentation.github.io/sphinx_typo3_theme_rendering_test/

I'm inclined to say however, that we should lock the rendering to a specific container release, as we had done with the old Bamboo plans. Otherwise there may be differences in rendering, which probably raises communication traffic.

**Comment by susannemoog** [comment]
Just ping me in Slack when you have time.
Locking the rendering to a specific version would be no problem (if you check this repo you can see that it's just adding the version basically). Differences in rendering will appear either way as long as we don't re-render everything as some manuals will be rendered sooner than others. For the new release: just let me know when it's tagged and I'll re-render everything.

**Comment by linawolf** [comment]
I think we do not need this and it would also be a security risk. We are doing the switch in the github action insteas as susi suggested
